# molecular_simulator/molecular_simulator/core/generators/vasp_generator.py
import os
      import numpy as np # Added for np.any checks
from ase import Atoms
from ase.io.vasp import write_vasp # For POSCAR
# For KPOINTS, we might need a helper or write it manually based on params.
# For INCAR, we'll construct it based on params.

def generate_vasp_scf_input(atoms: Atoms, scf_parameters: dict, output_path: str = ".", structure_filename: str = "POSCAR"):
    """
    Generates VASP input files for an SCF calculation.
    - atoms: ASE Atoms object.
    - scf_parameters: Dictionary with SCF parameters like ENCUT, KPOINTS_TUPLE, ISMEAR, SIGMA.
    - output_path: Directory where files will be saved.
    - structure_filename: Name for the structure file (POSCAR/CONTCAR).
    """
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    # 1. Write POSCAR
    poscar_path = os.path.join(output_path, structure_filename)
    # Ensure cell is defined for periodic systems, otherwise VASP might not behave as expected
    if not np.any(atoms.cell) and atoms.pbc.any():
        # Set a large vacuum box if no cell is defined but PBC is expected
        # This is a common practice for isolated molecules in VASP
        print("Warning: Atoms object has PBC enabled but no cell defined. Applying a default vacuum box of 60x60x60 Angstroms.")
        atoms.set_cell([60, 60, 60])
        atoms.center()
    elif not atoms.pbc.any() and np.any(atoms.cell):
        print("Warning: Atoms object has a cell defined but PBC is False. VASP is a periodic code. Consider enabling PBC.")
    elif not atoms.pbc.any() and not np.any(atoms.cell):
         print("Warning: Atoms object has no cell and PBC is False. VASP is a periodic code. Applying a default vacuum box of 60x60x60 Angstroms and enabling PBC.")
         atoms.set_cell([60, 60, 60])
         atoms.set_pbc(True)
         atoms.center()


    write_vasp(poscar_path, atoms, direct=True, sort=True, vasp5=True) # direct=True for fractional, sort for consistency

    # 2. Write INCAR
    incar_content = "# Basic SCF Calculation INCAR generated by MolecularSimulator

"
    incar_content += "SYSTEM = User_Structure_SCF
" # Could be derived from atoms or user input
    
    # General parameters often good for SCF
    incar_content += "PREC = Accurate
"
    incar_content += "IBRION = -1     # No ionic updates for SCF
"
    incar_content += "NSW = 0         # No ionic steps for SCF
"
    incar_content += "NELM = 100      # Max electronic steps
"
    incar_content += "EDIFF = 1E-6    # Energy convergence criterion
"
    incar_content += "LREAL = Auto    # Real-space projection
"
    incar_content += "ALGO = Normal   # Algorithm (Normal for most cases, could be Fast or VeryFast)
"
    incar_content += "LWAVE = .FALSE.   # Write WAVECAR or not
"
    incar_content += "LCHARG = .FALSE.  # Write CHGCAR or not

"


    # Parameters from scf_parameters dictionary
    encut = scf_parameters.get("ENCUT", 400) # Default 400 eV
    ismear = scf_parameters.get("ISMEAR", 0) # Gaussian smearing for semiconductor/insulator, 1 for metal
    sigma = scf_parameters.get("SIGMA", 0.05) # Smearing width

    incar_content += f"ENCUT = {encut}
"
    incar_content += f"ISMEAR = {ismear}
"
    incar_content += f"SIGMA = {sigma}
"
    
    # Add other parameters if provided
    extra_incar_params = scf_parameters.get("EXTRA_INCAR_PARAMS", {})
    for key, value in extra_incar_params.items():
        incar_content += f"{str(key).upper()} = {value}
"

    incar_path = os.path.join(output_path, "INCAR")
    with open(incar_path, "w") as f:
        f.write(incar_content)

    # 3. Write KPOINTS
    kpoints_tuple = scf_parameters.get("KPOINTS_TUPLE", (3, 3, 3)) # e.g., (kx, ky, kz)
    kpoints_content = "Automatic mesh
"
    kpoints_content += "0
" # 0 -> automatic generation scheme
    kpoints_content += "Gamma
" # Gamma centered for Monkhorst-Pack
    kpoints_content += f"{kpoints_tuple[0]} {kpoints_tuple[1]} {kpoints_tuple[2]}
"
    kpoints_content += "0 0 0
" # Optional shift

    kpoints_path = os.path.join(output_path, "KPOINTS")
    with open(kpoints_path, "w") as f:
        f.write(kpoints_content)

    # 4. POTCAR - User responsibility
    potcar_info_path = os.path.join(output_path, "POTCAR_README.txt")
    unique_elements = sorted(list(set(atoms.get_chemical_symbols())))
    with open(potcar_info_path, "w") as f:
        f.write("POTCAR file is NOT generated by this tool.
")
        f.write("You need to create it manually by concatenating the POTCAR files for the following elements:
")
        for el in unique_elements:
            f.write(f"- {el}
")
        f.write("Ensure they are in the same order as elements in your POSCAR file if using VASP default element ordering (after sorting by symbol).
")
        f.write(f"The order ASE typically writes sorted symbols to POSCAR is: {', '.join(unique_elements)}
")
    
    return [poscar_path, incar_path, kpoints_path, potcar_info_path]


def generate_vasp_geo_opt_input(atoms: Atoms, geo_opt_parameters: dict, output_path: str = ".", structure_filename: str = "POSCAR"):
    """
    Generates VASP input files for a Geometry Optimization calculation.
    - atoms: ASE Atoms object.
    - geo_opt_parameters: Dictionary with parameters like IBRION, NSW, EDIFFG, POTIM, ENCUT, etc.
    - output_path: Directory where files will be saved.
    - structure_filename: Name for the structure file (POSCAR/CONTCAR).
    """
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    # Basic checks for cell and PBC (especially if it's a molecule)
    if not np.any(atoms.cell) and not atoms.pbc.any(): # Isolated molecule (no cell, no PBC)
        print("Warning: No cell defined for geometry optimization. VASP might add a default cell.")
        # VASP typically requires a cell. If it's a molecule, user might want to add a large box.
        # For now, proceed, but this is a common pitfall for molecule calculations in VASP.
        # Consider adding a default large cell if atoms.cell is zero and pbc is False.
        # atoms.set_cell([20,20,20]) # Example default cell for isolated molecule
        # atoms.center()

    # 1. Write POSCAR
    poscar_path = os.path.join(output_path, structure_filename)
    write_vasp(poscar_path, atoms, direct=True, sort=True, vasp5=True)

    # 2. Write INCAR
    incar_content = "# Geometry Optimization INCAR generated by MolecularSimulator\n\n"
    incar_content += "SYSTEM = User_Structure_GeoOpt\n"
    
    # General electronic parameters
    incar_content += "PREC = Accurate\n"
    incar_content += "NELM = 100\n"
    incar_content += "EDIFF = 1E-6    # SCF convergence criterion\n"
    incar_content += "LREAL = Auto\n"
    incar_content += "ALGO = Normal   # Or Fast/VeryFast\n"
    incar_content += "LWAVE = .FALSE.\n"
    incar_content += "LCHARG = .FALSE.\n\n"

    # Ionic relaxation parameters from geo_opt_parameters
    ibrion = geo_opt_parameters.get("IBRION", 2)     # Default to CG
    nsw = geo_opt_parameters.get("NSW", 200)         # Default max steps
    ediffg = geo_opt_parameters.get("EDIFFG", "-0.01") # Default force convergence (eV/A)
    potim = geo_opt_parameters.get("POTIM", 0.2)     # Default step size for CG

    incar_content += f"IBRION = {ibrion}\n"
    incar_content += f"NSW = {nsw}\n"
    incar_content += f"EDIFFG = {ediffg}    # ediffg is a string\n" 
    if ibrion in [1, 2, 3]: # POTIM is mainly for these IBRION values
        incar_content += f"POTIM = {potim}\n"
    
    # Electronic parameters for during optimization
    encut = geo_opt_parameters.get("ENCUT", 400)
    ismear = geo_opt_parameters.get("ISMEAR", 0) # Gaussian for general, 1 for metals
    sigma = geo_opt_parameters.get("SIGMA", 0.05)

    incar_content += f"ENCUT = {encut}\n"
    incar_content += f"ISMEAR = {ismear}\n"
    incar_content += f"SIGMA = {sigma}\n\n"
    
    # Add other parameters if provided
    extra_incar_params = geo_opt_parameters.get("EXTRA_INCAR_PARAMS", {})
    for key, value in extra_incar_params.items():
        incar_content += f"{str(key).upper()} = {value}\n"

    incar_path = os.path.join(output_path, "INCAR")
    with open(incar_path, "w") as f:
        f.write(incar_content)

    # 3. Write KPOINTS (same logic as SCF for now)
    kpoints_tuple = geo_opt_parameters.get("KPOINTS_TUPLE", (3, 3, 3))
    kpoints_content = "Automatic mesh\n0\nGamma\n"
    kpoints_content += f"{kpoints_tuple[0]} {kpoints_tuple[1]} {kpoints_tuple[2]}\n0 0 0\n"
    kpoints_path = os.path.join(output_path, "KPOINTS")
    with open(kpoints_path, "w") as f:
        f.write(kpoints_content)

    # 4. POTCAR - User responsibility (same as SCF)
    potcar_info_path = os.path.join(output_path, "POTCAR_README.txt")
    unique_elements = sorted(list(set(atoms.get_chemical_symbols())))
    with open(potcar_info_path, "w") as f:
        f.write("POTCAR file is NOT generated by this tool.\n")
        f.write("You need to create it manually by concatenating the POTCAR files for the following elements:\n")
        for el in unique_elements: f.write(f"- {el}\n")
        f.write(f"Order for concatenation (ASE default sort): {', '.join(unique_elements)}\n")

    return [poscar_path, incar_path, kpoints_path, potcar_info_path]
